name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake contribution graph
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: EXA-Hub
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit and push changes to main
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.PAT_TOKEN }} # Use your Personal Access Token here
          branch: main
          add: "dist"
          message: "Generate Snake Animation"
          push: true